// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: resource.proto

package resource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneratePSUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	ResourceType  string                 `protobuf:"bytes,4,opt,name=ResourceType,proto3" json:"ResourceType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePSUrlRequest) Reset() {
	*x = GeneratePSUrlRequest{}
	mi := &file_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePSUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePSUrlRequest) ProtoMessage() {}

func (x *GeneratePSUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePSUrlRequest.ProtoReflect.Descriptor instead.
func (*GeneratePSUrlRequest) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratePSUrlRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GeneratePSUrlRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GeneratePSUrlRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *GeneratePSUrlRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type GeneratePSUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=UploadUrl,proto3" json:"UploadUrl,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=ObjectKey,proto3" json:"ObjectKey,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=ExpiresIn,proto3" json:"ExpiresIn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePSUrlResponse) Reset() {
	*x = GeneratePSUrlResponse{}
	mi := &file_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePSUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePSUrlResponse) ProtoMessage() {}

func (x *GeneratePSUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePSUrlResponse.ProtoReflect.Descriptor instead.
func (*GeneratePSUrlResponse) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratePSUrlResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GeneratePSUrlResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *GeneratePSUrlResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_resource_proto protoreflect.FileDescriptor

const file_resource_proto_rawDesc = "" +
	"\n" +
	"\x0eresource.proto\x12\bresource\"\x94\x01\n" +
	"\x14GeneratePSUrlRequest\x12\x1a\n" +
	"\bFileName\x18\x01 \x01(\tR\bFileName\x12 \n" +
	"\vContentType\x18\x02 \x01(\tR\vContentType\x12\x1a\n" +
	"\bFileSize\x18\x03 \x01(\x03R\bFileSize\x12\"\n" +
	"\fResourceType\x18\x04 \x01(\tR\fResourceType\"q\n" +
	"\x15GeneratePSUrlResponse\x12\x1c\n" +
	"\tUploadUrl\x18\x01 \x01(\tR\tUploadUrl\x12\x1c\n" +
	"\tObjectKey\x18\x02 \x01(\tR\tObjectKey\x12\x1c\n" +
	"\tExpiresIn\x18\x03 \x01(\x03R\tExpiresIn2c\n" +
	"\x0fResourceService\x12P\n" +
	"\rGeneratePSUrl\x12\x1e.resource.GeneratePSUrlRequest\x1a\x1f.resource.GeneratePSUrlResponseB Z\x1eshared/proto/resource;resourceb\x06proto3"

var (
	file_resource_proto_rawDescOnce sync.Once
	file_resource_proto_rawDescData []byte
)

func file_resource_proto_rawDescGZIP() []byte {
	file_resource_proto_rawDescOnce.Do(func() {
		file_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_proto_rawDesc), len(file_resource_proto_rawDesc)))
	})
	return file_resource_proto_rawDescData
}

var file_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_proto_goTypes = []any{
	(*GeneratePSUrlRequest)(nil),  // 0: resource.GeneratePSUrlRequest
	(*GeneratePSUrlResponse)(nil), // 1: resource.GeneratePSUrlResponse
}
var file_resource_proto_depIdxs = []int32{
	0, // 0: resource.ResourceService.GeneratePSUrl:input_type -> resource.GeneratePSUrlRequest
	1, // 1: resource.ResourceService.GeneratePSUrl:output_type -> resource.GeneratePSUrlResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resource_proto_init() }
func file_resource_proto_init() {
	if File_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_proto_rawDesc), len(file_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_proto_goTypes,
		DependencyIndexes: file_resource_proto_depIdxs,
		MessageInfos:      file_resource_proto_msgTypes,
	}.Build()
	File_resource_proto = out.File
	file_resource_proto_goTypes = nil
	file_resource_proto_depIdxs = nil
}
