syntax="proto3";
package job;
option go_package = "shared/proto/job;job";
service JobService {
    rpc CreateJob (CreateJobRequest) returns (CreateJobResponse);
    rpc GetJob (GetJobRequest) returns (GetJobResponse);
}

message CreateJobRequest{
    optional string ResourceID=1;
    string JobType=2;
    bytes Parameters=3;
}

message CreateJobResponse{
    string JobId = 1;
    string Status = 2;
}

message GetJobRequest{
    string JobId =1;
}

message GetJobResponse{
    string JobId = 1;
    optional string ResourceID = 2;
    string JobType = 3;
    string Status = 4;
    int32 RetryCount = 5;
    int32 MaxRetries = 6;
    optional string ErrorMessage = 7;
    optional string OutputResourceID = 8;
    string CreatedAt = 9;
    optional string StartedAt = 10;
    optional string CompletedAt = 11;
}