// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: job.proto

package job

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceID    *string                `protobuf:"bytes,1,opt,name=ResourceID,proto3,oneof" json:"ResourceID,omitempty"`
	JobType       string                 `protobuf:"bytes,2,opt,name=JobType,proto3" json:"JobType,omitempty"`
	Parameters    []byte                 `protobuf:"bytes,3,opt,name=Parameters,proto3" json:"Parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{0}
}

func (x *CreateJobRequest) GetResourceID() string {
	if x != nil && x.ResourceID != nil {
		return *x.ResourceID
	}
	return ""
}

func (x *CreateJobRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *CreateJobRequest) GetParameters() []byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type CreateJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobResponse) Reset() {
	*x = CreateJobResponse{}
	mi := &file_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobResponse) ProtoMessage() {}

func (x *CreateJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobResponse.ProtoReflect.Descriptor instead.
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CreateJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            string                 `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
	ResourceID       *string                `protobuf:"bytes,2,opt,name=ResourceID,proto3,oneof" json:"ResourceID,omitempty"`
	JobType          string                 `protobuf:"bytes,3,opt,name=JobType,proto3" json:"JobType,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	RetryCount       int32                  `protobuf:"varint,5,opt,name=RetryCount,proto3" json:"RetryCount,omitempty"`
	MaxRetries       int32                  `protobuf:"varint,6,opt,name=MaxRetries,proto3" json:"MaxRetries,omitempty"`
	ErrorMessage     *string                `protobuf:"bytes,7,opt,name=ErrorMessage,proto3,oneof" json:"ErrorMessage,omitempty"`
	OutputResourceID *string                `protobuf:"bytes,8,opt,name=OutputResourceID,proto3,oneof" json:"OutputResourceID,omitempty"`
	Parameters       []byte                 `protobuf:"bytes,12,opt,name=Parameters,proto3" json:"Parameters,omitempty"`
	Metadata         []byte                 `protobuf:"bytes,13,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,9,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	StartedAt        *string                `protobuf:"bytes,10,opt,name=StartedAt,proto3,oneof" json:"StartedAt,omitempty"`
	CompletedAt      *string                `protobuf:"bytes,11,opt,name=CompletedAt,proto3,oneof" json:"CompletedAt,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobResponse) GetResourceID() string {
	if x != nil && x.ResourceID != nil {
		return *x.ResourceID
	}
	return ""
}

func (x *GetJobResponse) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *GetJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetJobResponse) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *GetJobResponse) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *GetJobResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *GetJobResponse) GetOutputResourceID() string {
	if x != nil && x.OutputResourceID != nil {
		return *x.OutputResourceID
	}
	return ""
}

func (x *GetJobResponse) GetParameters() []byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *GetJobResponse) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetJobResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetJobResponse) GetStartedAt() string {
	if x != nil && x.StartedAt != nil {
		return *x.StartedAt
	}
	return ""
}

func (x *GetJobResponse) GetCompletedAt() string {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return ""
}

var File_job_proto protoreflect.FileDescriptor

const file_job_proto_rawDesc = "" +
	"\n" +
	"\tjob.proto\x12\x03job\"\x80\x01\n" +
	"\x10CreateJobRequest\x12#\n" +
	"\n" +
	"ResourceID\x18\x01 \x01(\tH\x00R\n" +
	"ResourceID\x88\x01\x01\x12\x18\n" +
	"\aJobType\x18\x02 \x01(\tR\aJobType\x12\x1e\n" +
	"\n" +
	"Parameters\x18\x03 \x01(\fR\n" +
	"ParametersB\r\n" +
	"\v_ResourceID\"A\n" +
	"\x11CreateJobResponse\x12\x14\n" +
	"\x05JobId\x18\x01 \x01(\tR\x05JobId\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\tR\x06Status\"%\n" +
	"\rGetJobRequest\x12\x14\n" +
	"\x05JobId\x18\x01 \x01(\tR\x05JobId\"\x8e\x04\n" +
	"\x0eGetJobResponse\x12\x14\n" +
	"\x05JobId\x18\x01 \x01(\tR\x05JobId\x12#\n" +
	"\n" +
	"ResourceID\x18\x02 \x01(\tH\x00R\n" +
	"ResourceID\x88\x01\x01\x12\x18\n" +
	"\aJobType\x18\x03 \x01(\tR\aJobType\x12\x16\n" +
	"\x06Status\x18\x04 \x01(\tR\x06Status\x12\x1e\n" +
	"\n" +
	"RetryCount\x18\x05 \x01(\x05R\n" +
	"RetryCount\x12\x1e\n" +
	"\n" +
	"MaxRetries\x18\x06 \x01(\x05R\n" +
	"MaxRetries\x12'\n" +
	"\fErrorMessage\x18\a \x01(\tH\x01R\fErrorMessage\x88\x01\x01\x12/\n" +
	"\x10OutputResourceID\x18\b \x01(\tH\x02R\x10OutputResourceID\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"Parameters\x18\f \x01(\fR\n" +
	"Parameters\x12\x1a\n" +
	"\bMetadata\x18\r \x01(\fR\bMetadata\x12\x1c\n" +
	"\tCreatedAt\x18\t \x01(\tR\tCreatedAt\x12!\n" +
	"\tStartedAt\x18\n" +
	" \x01(\tH\x03R\tStartedAt\x88\x01\x01\x12%\n" +
	"\vCompletedAt\x18\v \x01(\tH\x04R\vCompletedAt\x88\x01\x01B\r\n" +
	"\v_ResourceIDB\x0f\n" +
	"\r_ErrorMessageB\x13\n" +
	"\x11_OutputResourceIDB\f\n" +
	"\n" +
	"_StartedAtB\x0e\n" +
	"\f_CompletedAt2{\n" +
	"\n" +
	"JobService\x12:\n" +
	"\tCreateJob\x12\x15.job.CreateJobRequest\x1a\x16.job.CreateJobResponse\x121\n" +
	"\x06GetJob\x12\x12.job.GetJobRequest\x1a\x13.job.GetJobResponseB\x16Z\x14shared/proto/job;jobb\x06proto3"

var (
	file_job_proto_rawDescOnce sync.Once
	file_job_proto_rawDescData []byte
)

func file_job_proto_rawDescGZIP() []byte {
	file_job_proto_rawDescOnce.Do(func() {
		file_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)))
	})
	return file_job_proto_rawDescData
}

var file_job_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_job_proto_goTypes = []any{
	(*CreateJobRequest)(nil),  // 0: job.CreateJobRequest
	(*CreateJobResponse)(nil), // 1: job.CreateJobResponse
	(*GetJobRequest)(nil),     // 2: job.GetJobRequest
	(*GetJobResponse)(nil),    // 3: job.GetJobResponse
}
var file_job_proto_depIdxs = []int32{
	0, // 0: job.JobService.CreateJob:input_type -> job.CreateJobRequest
	2, // 1: job.JobService.GetJob:input_type -> job.GetJobRequest
	1, // 2: job.JobService.CreateJob:output_type -> job.CreateJobResponse
	3, // 3: job.JobService.GetJob:output_type -> job.GetJobResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_job_proto_init() }
func file_job_proto_init() {
	if File_job_proto != nil {
		return
	}
	file_job_proto_msgTypes[0].OneofWrappers = []any{}
	file_job_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_proto_goTypes,
		DependencyIndexes: file_job_proto_depIdxs,
		MessageInfos:      file_job_proto_msgTypes,
	}.Build()
	File_job_proto = out.File
	file_job_proto_goTypes = nil
	file_job_proto_depIdxs = nil
}
