apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect
  template:
    metadata:
      labels:
        app: connect
    spec:
      containers:
        - name: connect
          image: quay.io/debezium/connect:2.4
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1536Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8083
          readinessProbe:
            httpGet:
              path: /connectors
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
          env:
            - name: BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: GROUP_ID
              value: "1"
            - name: CONFIG_STORAGE_TOPIC
              value: "my_connect_configs"
            - name: OFFSET_STORAGE_TOPIC
              value: "my_connect_offsets"
            - name: STATUS_STORAGE_TOPIC
              value: "my_connect_statuses"
            - name: CONFIG_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: OFFSET_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: STATUS_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: KAFKA_HEAP_OPTS
              value: "-Xms256M -Xmx512M"
            - name: CONNECT_PLUGIN_PATH
              value: "/kafka/connect"
            - name: VALUE_CONVERTER_SCHEMAS_ENABLE
              value: "false"
            - name: KEY_CONVERTER_SCHEMAS_ENABLE
              value: "false"


---
apiVersion: v1
kind: Service
metadata:
  name: connect
spec:
  selector:
    app: connect
  ports:
    - port: 8083
      targetPort: 8083
