apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
type: Opaque
stringData:
  root-user: 
  root-password: 
  db-name: 

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-auth
type: Opaque
stringData:
  root-user: 
  root-password: 
